<?php

/**
 * @file
 * Primary module hooks for Site location module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme().
 */
function site_location_theme() {
  return [
    'site_location_rendering' => [
      'variables' => [
        'date_value' => NULL,
        'timezone_value' => NULL
      ],
    ],
  ];
}
